repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: conda run --name dragonbornleveler python -m pytest
        language: system
        pass_filenames: false
        always_run: true
